Add 24hr count to /online_collectors route
orcfax/itn-api pull request #3
Opened 2024-12-30 21:42 UTC by whankinsiv

Changes:
1. Modified /online_collectors route to also query 24 hour count. 
2. Modified participants_count_table helper function to add 24 hour count to table
3. Modified READ_ME file to fix typo

2025-01-14 16:41 UTC, ross-spencer requested changes
Looks pretty good Will. I'd like to move forward with adding the capability with the requested changes.

Once you've made those, can you also run:

```sh
python -m tox -e linting
```

There's a small change I am keen to make to the locations table via #4 but this needs to be considered a bit more.

2025-01-14 16:41 UTC, ross-spencer commented on src/itn_api/api.py
> +import folium
It looks like this dependency needs to be added in the requirements.txt for the repo to work.

2025-01-14 16:41 UTC, ross-spencer commented on src/itn_api/htm_helpers.py
> +    collectors_map = folium.Map(location=[0.0, 0.0], zoom_start=1, min_zoom=1, zoom_control=False, attr=" ")
folium needs to be imported above

2025-01-14 16:41 UTC, ross-spencer commented on src/itn_api/htm_helpers.py
> +def locations_map(locations):
This folium map looks really cool, but I'm not sure why you're replace a table output with it and not simply create a new endpoint? 

For example, I'm looking at adding staking key to the table, but this is harder to do with the map output. 

Are you able to add this as a new endpoint?

NB. It's feasible for different websites to use these different endpoints, so our little diagnostics page might not use it, but it's nice to have the option, e.g. you can call it locally.

2025-01-14 16:41 UTC, ross-spencer commented on src/itn_api/api.py
> +             "SELECT address, COUNT(*) AS total_count, SUM(CASE WHEN datetime(date_time) >= datetime('now', '-1 day') THEN 1 ELSE 0 END) AS count_24hr FROM data_points GROUP BY address ORDER BY total
Nice, I didn't know about this function. Super helpful!

2025-01-14 19:46 UTC, whankinsiv commented on src/itn_api/htm_helpers.py
> +def locations_map(locations):
I added the locations_table helper function back and returned the /locations route to display the table. I made a new route /locations_map to return the locations map.

2025-01-15 14:07 UTC, closed without merging

2025-01-15 14:08 UTC, ross-spencer commented
Edit: via 3610a1026 where your handle is properly referenced.